---
include: [
    {project: kube/temp/pmp, file: ez-temp.yaml, ref: main}
    ]
stages: [prepare, build, deploy, release, publish]

variables:
    KUBES: |
      _ENV_/configmap
      _ENV_/secret
      deployment
